### ISSUE TITLE
`count()` function no longer works on v0.19.0

### ISSUE THREAD

**Issue by SadMachinesP86** [AmrDeveloper/GQL#101]
**Describe the bug**
Any usage of `count()` results in an error `Function 'count' argument number 0 with type '(some type)' don't match expected type 'Integer'`.

**To Reproduce**
1. Upgrade to v0.19.0
2. Enter GQL console in any repo
3. Try any `count()`, query, i.e. `select count(commit_id) from commits`

```
gql > select count(commit_id) from commits
[Error]: Function `count` argument number 0 with type `Text` don't match expected type `Integer`
=> Column 12 to 12,
  |
1 | select count(commit_id) from commits
  | ------------^
  |
```

**Expected behavior**
On v0.18.0, this returns the following:
```
gql > select count(commit_id) from commits
╭──────────╮
│ column_2 │
╞══════════╡
│ 27       │
╰──────────╯
```

**Screenshots**
N/A (output provided)

**GQL (please complete the following information):**
 - v0.19.0

**Comment by AmrDeveloper** [comment]
Hello @SadMachinesP86,

Thank you so much for fast reporting, it fixed now on `0.19.1`

Thank you,
Amr
