### ISSUE TITLE
Crash if right-hand of expression is string without double quotation marks

### ISSUE THREAD

**Issue by phynalle** [AmrDeveloper/GQL#11]
**Describe the bug**

I tried this. `select name from branches where name starts_with xxx`

and the program is crashed. but "xxx" was fine.

**To Reproduce**
`gql > select name from branches where name starts_with x`

**Expected behavior**
I don't know the right spec. but it should guide correct way or display a result.

**Screenshots**
![image](https://github.com/AmrDeveloper/GQL/assets/6007810/4bbc7629-896d-42db-95bd-63b704e92d32)

**GQL (please complete the following information):**
 - Version = 0.3.0

**Comment by AmrDeveloper** [comment]
Hello @phynalle,

String must has double quotes, in your code x and xxx expected to be field name or alias name.

I am working on resolver and checker for next release to provide clear error messages

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
@phynalle Solved at `0.6.0`

**Comment by AmrDeveloper** [comment]
Fixed and released on `0.8.0`
