### ISSUE TITLE
View insertions, deletions, and files changed by commit

### ISSUE THREAD

**Issue by Danation** [AmrDeveloper/GQL#112]
**Is your feature request related to a problem? Please describe.**

I really like the command for querying author contributions:

`SELECT author_name, COUNT(author_name) AS commit_num FROM commits WHERE datetime > "2024-01-01 00:00:00" GROUP BY author_name ORDER BY commit_num DESC`

I especially like that this can be run across many repos at once.  That is an excellent and unique feature.

However, from this I cannot view information about insertions, deletions, and files changed.

I see that there is a diffs table, but it cannot be filtered by datetime or branch.  It is also very expensive to query.  I also don't see a way to join commits to diffs.

**Describe the solution you'd like**

Include insertions, deletions, and file count in commits table.

**Describe alternatives you've considered**

- Include a way to filter diffs by date and branch.
- Include a way to join commits and diffs

**Additional context**

**Comment by AmrDeveloper** [comment]
Hello @Danation,

Thanks you suggestion, Now i added datetime to the diffs table and also you will be able to join commits with diffs using commits id, author name...etc, but still working on ON expression for join

Thank you

**Comment by AmrDeveloper** [comment]
Solved on `0.25.0`
