### ISSUE TITLE
output of group by

### ISSUE THREAD

**Issue by fdncred** [AmrDeveloper/GQL#117]
**Describe the bug**
I expected this query to produce 1 row. The
```nushell
❯ ^gitql -q 'select author_name, count(author_name) AS auth_count from commits group by author_name order by count(author_name)'
╭──────────────────┬────────────╮
│ author_name      ┆ auth_count │
╞══════════════════╪════════════╡
│ Darren Schroeder ┆ 6          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder ┆ 6          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder ┆ 6          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder ┆ 6          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder ┆ 6          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder ┆ 6          │
╰──────────────────┴────────────╯
```
There are indeed 6 commits, but shouldn't group by only show the aggregate of 1?
```nushell
❯ ^gitql -q 'select author_name from commits'
╭──────────────────╮
│ author_name      │
╞══════════════════╡
│ Darren Schroeder │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Darren Schroeder │
╰──────────────────╯
```
**GQL (please complete the following information):**
❯ ^gitql --version
GitQL version 0.27.0

**Comment by AmrDeveloper** [comment]
Thank you for reporting @fdncred,

This is important to handled

**Comment by AmrDeveloper** [comment]
It fixed now, you can run the query from issue description and get good result, 

Thanks for reporting, i will release it next version

**Comment by fdncred** [comment]
Thanks. I'm trying to integrate into a nushell plugin and was wondering why my code didn't work. Then I tried your cli and found out the results were the same. 🤣 Thanks for working on this. I'll try and test it in the next day or so.

**Comment by AmrDeveloper** [comment]
Thats cool idea to integrate it with nushell plugin,

**Comment by fdncred** [comment]
prototype
![image](https://github.com/user-attachments/assets/8dd2619d-a47b-4882-b74d-3239db6707ef)

**Comment by AmrDeveloper** [comment]
> prototype
> ![image](https://github.com/user-attachments/assets/8dd2619d-a47b-4882-b74d-3239db6707ef)
> 

Cool 😅

**Comment by AmrDeveloper** [comment]
I think we can close this

**Comment by fdncred** [comment]
Thanks for your help! I'm really enjoying GQL!

**Comment by AmrDeveloper** [comment]
> Thanks for your help! I'm really enjoying GQL!

Thank you, i think it can be even better when implementing line editor, sub query, user defined functions, some optimisations and tree rewriting, but step by step :D
