### ISSUE TITLE
Implement SQL String functions with documentations

### ISSUE THREAD

**Issue by AmrDeveloper** [AmrDeveloper/GQL#13]
Implement string function in our engine, one per pull request.

Steps:
- Choose unimplemented function and write `I am on <function_name>`.
- Then start implement the function in `crates/gitql-ast/function.rs`.
- Add docs for it in `docs/function/function.md`.
- Make sure everything is formatted and submit a Pull Request.
- Don't forget to mention issue number in pull request title.

### Text Functions
- [x] ASCII
- [x] CHAR
- [x] CHARINDEX
- [x] CONCAT
- [x] DATALENGTH
- [ ] DIFFERENCE
- [ ] FORMAT
- [x] LEFT
- [x] LEN
- [x] LOWER
- [x] LTRIM
- [x] NCHAR
- [ ] PATINDEX
- [x] QUOTENAME
- [x] REPLACE
- [x] REPLICATE
- [x] REVERSE
- [x] RIGHT
- [x] RTRIM
- [x] SOUNDEX
- [x] SPACE
- [x] STR
- [x] STUFF
- [x] SUBSTRING
- [x] TRANSLATE
- [x] TRIM
- [x] UNICODE
- [x] UPPER

For more information about implementation and description check https://www.w3schools.com/sql/sql_ref_sqlserver.asp

Note: You can only open max 3 PR at the time

**Comment by Lilit0x** [comment]
I am on ASCII

**Comment by Lilit0x** [comment]
I am on CHAR

**Comment by Lilit0x** [comment]
@AmrDeveloper , the CHARINDEX function might be tricky since the last argument is optional, but the condition checks if the specified arguments match, I mean [here](https://github.com/AmrDeveloper/GQL/blob/180be8766182a7c74024e988487099decdbfcfa0/crates/gitql-parser/src/parser.rs#L1234) .

**Comment by Lilit0x** [comment]
I am on DATELENGTH

**Comment by AmrDeveloper** [comment]
> @AmrDeveloper , the CHARINDEX function might be tricky since the last argument is optional, but the condition checks if the specified arguments match, I mean [here](https://github.com/AmrDeveloper/GQL/blob/180be8766182a7c74024e988487099decdbfcfa0/crates/gitql-parser/src/parser.rs#L1234) .

You are right some functions we will delay them until do some improvements in type system

**Comment by Lilit0x** [comment]
I am on LEFT

**Comment by Lilit0x** [comment]
@AmrDeveloper, is there a difference between the implementation of `NCHAR` and `CHAR` at least in Rust, since all characters are just `u32`s under the hood and just casting from the number will be the same.

**Comment by AmrDeveloper** [comment]
> `NCHAR`

You are right, we can ignore it for now and maybe if needed we can pass the the char function to it

**Comment by Lilit0x** [comment]
> > `NCHAR`
> 
> You are right, we can ignore it for now and maybe if needed we can pass the the char function to it

Yeahh, that was I planned on doing, wanted to get your approval on it.

**Comment by Lilit0x** [comment]
I am on PATINDEX

**Comment by AmrDeveloper** [comment]
> > > `NCHAR`
> > 
> > 
> > You are right, we can ignore it for now and maybe if needed we can pass the the char function to it
> 
> Yeahh, that was I planned on doing, wanted to get your approval on it.

I faced the same problem in Date functions too we need to decide if we should duplicate them or take only one

**Comment by Lilit0x** [comment]
> > > > `NCHAR`
> > > 
> > > 
> > > You are right, we can ignore it for now and maybe if needed we can pass the the char function to it
> > 
> > 
> > Yeahh, that was I planned on doing, wanted to get your approval on it.
> 
> I faced the same problem in Date functions too we need to decide if we should duplicate them or take only one

We could just use different names for them but they'll still be the same function. What I mean is:
```rust
  map.insert("char", text_char);
  map.insert("nchar", text_char);
```
And we do the same in the `PROTOTYPES` hashmap too

**Comment by Lilit0x** [comment]
I am on REPLACE

**Comment by Lilit0x** [comment]
I am on RIGHT

**Comment by Lilit0x** [comment]
I am on STUFF

**Comment by Lilit0x** [comment]
I am on SUBSTRING

**Comment by Lilit0x** [comment]
I am on TRANSLATE

**Comment by AmrDeveloper** [comment]
@Lilit0x Lets keep next PR one by one it will be fast to review and merge

**Comment by Lilit0x** [comment]
Okay, got it.

**Comment by Lilit0x** [comment]
I am on SOUNDEX

**Comment by tbro** [comment]
I am on CONCAT

**Comment by tbro** [comment]
I am on UNICODE

**Comment by mobley-trent** [comment]
I am on CHARINDEX

**Comment by mobley-trent** [comment]
Hello @AmrDeveloper how do we handle optional arguments ?

**Comment by AmrDeveloper** [comment]
@mobley-trent Optional type is not implemented yet, i just implemented Variant and will implement Option soon

**Comment by AmrDeveloper** [comment]
@mobley-trent Now support Optional and varargs types

**Comment by frectonz** [comment]
@AmrDeveloper `NCHAR` is already implemented but it's not marked as complete in the task list.

![2024-02-26T04:57:57,788529872+03:00](https://github.com/AmrDeveloper/GQL/assets/53809656/0a3dfb81-af21-43a4-bc46-699809f67b01)

**Comment by frectonz** [comment]
I am on QUOTENAME
