### ISSUE TITLE
Releases with binary assets?

### ISSUE THREAD

**Issue by jankatins** [AmrDeveloper/GQL#2]
Any chance to get releases with binary assets, so one can download the compiled binary instead of needing to setup the toolchain and all that?

The rye release workflow looks nice: https://github.com/mitsuhiko/rye/blob/main/.github/workflows/release.yml

If there is a new tag, the workflow would create a draft release, compile all the assets (different architectures) and upload them to the release. The final step is then for somone to (manually) add the release description (if you have any) and publish the release.

(Creating only a draft and only publish when the description is filled is nice because upon publish, GitHub send out an email with the current content. If the release is created without a description, the email has no info :⁠-⁠()

**Comment by AmrDeveloper** [comment]
Thank you @jankatins for sharing link i will setup it soon and also build, test and docs actions

**Comment by AmrDeveloper** [comment]
I have finished the setup of Release Github actions, it harder than the sample because git2 require openssl setup on each platform.

Thank you @jankatins again for the suggestion and enjoy GQL :D
