### ISSUE TITLE
Implement SQL Date and Time functions with documentations

### ISSUE THREAD

**Issue by AmrDeveloper** [AmrDeveloper/GQL#24]
Implement one function with documentations pre pull request 

Steps:
- Choose unimplemented function and write `I am on <function_name>`.
- Then start implement the function in `crates/gitql-ast/function.rs`.
- Date functions to use or add are in `crates/gitql-ast/date_utils.rs`.
- Add docs for it in `docs/function/function.md`.
- Make sure everything is formatted and submit a Pull Request.

Note: Engine function don't care about implicit casting so for example `DAY("2017-06-15")` the argument you will got is `Date` type as described on the site not Text.

### Date Functions
- [X] CURRENT_DATE
- [X] CURRENT_TIME
- [X] CURRENT_TIMESTAMP
- [ ] DATE
- [x] DAYNAME
- [x] DAYOFMONTH
- [x] DAYOFWEEK
- [x] DAYOFYEAR
- [x] HOUR
- [x] LAST_DAY
- [x] MAKEDATE
- [x] MAKETIME
- [x] MINUTE
- [ ] MONTH
- [x] MONTHNAME
- [x] NOW
- [x] QUARTER
- [x] TO_DAYS
- [x] WEEK
- [x] WEEKDAY
- [ ] WEEKOFYEAR
- [x] YEAR
- [ ] YEARWEEK

For more information about implementation and description check https://www.w3schools.com/sql/sql_ref_sqlserver.asp

Note: You can only open max 3 PR at the time

**Comment by se-omarayman** [comment]
I am on NOW

**Comment by se-omarayman** [comment]
also i noticed that SELECT CURRENT_DATE()  returns a timestamp, while in sql it returns the date in yyyy-mm-dd format.
is this intended or a bug that should be fixed?

**Comment by AmrDeveloper** [comment]
> also i noticed that SELECT CURRENT_DATE() returns a timestamp, while in sql it returns the date in yyyy-mm-dd format. is this intended or a bug that should be fixed?

You are right, its intended to represent the internal value of Date and DateTime as time stamp i64 so we can perform apply operators on them and at the end the literal representation should be formatted date, 

https://github.com/AmrDeveloper/GQL/blob/1ce07fd7bfaaf196a79e271825c61f6a05d098cc/crates/gitql-ast/src/value.rs#L229

I will update the literal representation now

**Comment by mobley-trent** [comment]
I am on DAYNAME

**Comment by mobley-trent** [comment]
I am on MONTHNAME

**Comment by mobley-trent** [comment]
I am on DAYOFYEAR

**Comment by mobley-trent** [comment]
I am on HOUR

**Comment by frectonz** [comment]
I am on YEAR

**Comment by frectonz** [comment]
I am on MONTH

**Comment by frectonz** [comment]
I am on LAST_DAY

**Comment by frectonz** [comment]
I am on MINUTE

**Comment by frectonz** [comment]
I am on WEEKDAY
