### ISSUE TITLE
Use `cargo clippy` in project

### ISSUE THREAD

**Issue by nicklimmm** [AmrDeveloper/GQL#36]
**Is your feature request related to a problem? Please describe.**
Not a major blocker, but it would be great to include `clippy` to avoid bugs and standardize code style.

For example, the code below is blocked by `clippy::derive_ord_xor_partial_ord` lint [(details)](https://rust-lang.github.io/rust-clippy/master/index.html#derive_ord_xor_partial_ord)

https://github.com/AmrDeveloper/GQL/blob/4ea4428f07981d8fc808074e26f4228576afd835/crates/gitql-ast/src/value.rs#L39

Based on [`std::cmp::Ord`'s documentation](https://doc.rust-lang.org/std/cmp/trait.Ord.html),

> Trait for types that form a [total order](https://en.wikipedia.org/wiki/Total_order).
> 
> Implementations must be consistent with the [PartialOrd](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) implementation, and ensure max, min, and clamp are consistent with cmp:
> 
> partial_cmp(a, b) == Some(cmp(a, b)).
> ...
> It’s easy to accidentally make cmp and partial_cmp disagree by deriving some of the traits and manually implementing others.

And the current `Ord` impl for `Value` in `gitql-ast` violates the above requirements with the test case below,
```rust
let v1 = Value::Integer(1);
let v2 = Value::Boolean(true);
assert_eq!(Some(v1.cmp(&v2)), v1.partial_cmp(&v2)); // failed, `Some(Equal)` vs `Some(Less)`
```

Another thing: in `gitql-ast` crate alone, `clippy` outputs below (most of them are `needless_return`), which is quite concerning,
```bash
warning: `gitql-ast` (lib) generated 74 warnings
error: could not compile `gitql-ast` (lib) due to previous error; 74 warnings emitted
```

**Describe the solution you'd like**
- [ ] Add `cargo clippy` step in GitHub Actions (fail if it produces warnings and above)
- [ ] Fix `clippy` issues
- [ ] Reconsider implementation of `PartialOrd` and `Ord` for `Value` in `gitql-ast`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AmrDeveloper** [comment]
Thanks for suggestions, i will work on it soon

**Comment by nicklimmm** [comment]
@AmrDeveloper I can help to fix simple lint warnings, e.g. `needless_return`, if you prefer (just let me know though)

**Comment by AmrDeveloper** [comment]
> @AmrDeveloper I can help to fix simple lint warnings, e.g. `needless_return`, if you prefer (just let me know though)

Great, once i setup it i will mention you

Thanks

**Comment by AmrDeveloper** [comment]
@nicklimmm Done, we can close it now
