### ISSUE TITLE
DateTime filters don't seem to work

### ISSUE THREAD

**Issue by brunomenezes66** [AmrDeveloper/GQL#41]
When doing a query on the commits table, filtering on the time column does not work. 

Examples:
`select * from commits where time < "2023-11-01"`
Returns every single record on the table regardless of its time value.

`select * from commits where time < "2023-11-01"`
Returns nothing.

I´ve tried both using a "date" using quotes, a datetime also using quotes, and even using the result of a function such as MAKEDATE, none of them seem to work.
What seems to happen is that any value that is used to filter the time column is "bigger", so any greater than or equal filters always return nothing and any smaller than filter always work as no filter at all.

Tested on version v0.8.0, installed using cargo install.

**Comment by AmrDeveloper** [comment]
Hello @brunomenezes66,

I fixed the type checker between date and text to report error for type because implicit casting is not implemented yet so it see "2023-11-01" as Text not Date.

**Comment by AmrDeveloper** [comment]
Hello @brunomenezes66,

Time, Date and DateTime filtering and casting are now implemented and will be on the next release 👍🏻 

Thank you,
Amr Hesham

**Comment by AmrDeveloper** [comment]
Time, Date and DateTime filtering are available now on 0.9.0

@brunomenezes66

**Comment by AmrDeveloper** [comment]
Solved on `0.9.0`
