### ISSUE TITLE
EOF/script input, default repo, and plain-text output

### ISSUE THREAD

**Issue by jhheider** [AmrDeveloper/GQL#44]
Very cool project. Three features I could see being immediately useful:

- EOF support for piped input; currently `echo SELECT 1 | gitql -r .` goes into a loop redisplaying its prompt forever. `echo 'SELECT 1\nexit' | gitql -r .` works
- script file support; `echo SELECT 1 >foo.sql; gitql -r . foo.sql` would be useful.
- default repo: `echo SELECT 1\\nexit | gitql` should probably look for the repo in . (and possibly walk up .. until it finds a .git or hits /).
- plain-text, csv, or json output: `gitql -r . foo.sql --csv` would be very useful in pipelines to work with the resultant data without the ascii tables.

I may work on some PRs for some of these as time permits (assuming they're not against some philosophy of the project). This is a very cool idea, and these would address a wider range of use cases.

**Comment by AmrDeveloper** [comment]
Hello @jhheider,

Thank you for your suggestion all of them are very good for the project, we just need to order them and check requirements for example we need to revamp the CLI args parser and remove clap so we can easy add git files for current path as default value.

I will do small research and found requirements then create feature request issue for each point so you, me or anyone else can pick one and work on it

Thank you,
Amr Hesham

**Comment by jhheider** [comment]
No problem! I know people like to ask for stuff, so hopefully you find these suggestions useful as customer-discovery, if nothing else. :)

**Comment by AmrDeveloper** [comment]
I have implemented two feature request

- [x] EOF support for piped input;
```rs
echo 'SELECT CURRENT_DATE()' | ./gitql.exe -r ../..
```

- [x] gitql should probably look for the repo in .
```sh
echo 'SELECT 1' | gitql
```

TODO
- Script file support
- Plain-text, csv, or json output

**Comment by AmrDeveloper** [comment]
Thanks for suggestions, enjoy more is coming :D

**Comment by AmrDeveloper** [comment]
- [x] Output as `JSON` or `CSV`

**Comment by AmrDeveloper** [comment]
Current todo is

- [ ] Script file support

**Comment by galenseilis** [comment]
> Current todo is
> 
> * [ ]  Script file support

This would be great. I was just about to open a feature request for this when I saw this issue open.

**Comment by AmrDeveloper** [comment]
Yes i think this is one of the most important features beside supporting subqueries

**Comment by AmrDeveloper** [comment]
Now all feature are implemented, `gitql -s script.sql` is working fine

Thank you for suggestions

**Comment by galenseilis** [comment]
> Now all feature are implemented, `gitql -s script.sql` is working fine
> 
> Thank you for suggestions

Yup, I just tried this with a toy example and confirmed that it works with the main branch of [DESimpy](https://github.com/galenseilis/DESimpy/tree/main).

```sql
-- foo.sql
select * from commits
```

```bash
gql -s foo.sql
```
