### ISSUE TITLE
Allow to see the commit id when selecting from the commits table

### ISSUE THREAD

**Issue by Jeansidharta** [AmrDeveloper/GQL#5]
**Is your feature request related to a problem? Please describe.**
I would like to see the id of the commits table

**Describe the solution you'd like**
Adding a "commit_id" column to the commits table would probably do it

**Describe alternatives you've considered**
I don't see any other alternatives

**Additional context**
I think this would expand the use cases of this project a lot. You'd be able to checkout to a commit you just queried

**Comment by AmrDeveloper** [comment]
Hello @Jeansidharta,

Thank you for suggestion, i am totally agree with you and we can implement it easily

Thank you,
Amr Hesham

**Comment by AmrDeveloper** [comment]
@Jeansidharta Done it's implemented now :D

Enjoy GQL

**Comment by AmrDeveloper** [comment]
Done in release `0.3.0`
