### ISSUE TITLE
WinGet installation command name incorrect

### ISSUE THREAD

**Issue by allout58** [AmrDeveloper/GQL#51]
**Describe the bug**
When installing through WinGet, the command name is `gql-x86_64-windows.exe`, rather than `gitql` as expected

**To Reproduce**
1. Install through winget (`winget install gitql`)
2. Try to run `gitql`

**Expected behavior**
To be able to run `gitql` from the command line

**Screenshots**
![image](https://github.com/AmrDeveloper/GQL/assets/2939703/aab9d8c1-db10-41f2-8df0-03902c20a20e)

**GQL (please complete the following information):**
 - Version [e.g. 1.0.0]

**Additional context**
It seems like you can just add the following to the winget [`installer` manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/amrdeveloper/gitql/0.7.1/amrdeveloper.gitql.installer.yaml): 
```yaml
Commands:
- gitql
``` 
(I know very little about winget, I just happened to see a CLI tool I recognized and looked how they did it: https://github.com/microsoft/winget-pkgs/blob/e708f1e2c6fc5724b07f5c8c1ef54f5e939d3917/manifests/a/acaudwell/Gource/0.53/acaudwell.Gource.installer.yaml#L15C1-L16C1)

**Comment by AmrDeveloper** [comment]
Thank you for reporting i will update the installer file @allout58

**Comment by AmrDeveloper** [comment]
Fixed at this PR for current version `0.10.0`

https://github.com/microsoft/winget-pkgs/pull/129708#issuecomment-1867862419

**Comment by AmrDeveloper** [comment]
Fixed
