### ISSUE TITLE
Aggregation fails with Date fields

### ISSUE THREAD

**Issue by lmrlyv** [AmrDeveloper/GQL#55]
**Describe the bug**
Unlike SQL, it seems like GQL only allows aggregation on the Integer fields as it throws an error when using aggregation functions on the Date fields. For instance, the following query fails:

*Query*:
`select name, max(datetime) from commits group by name`

*Error message*:
"Compiletime ERROR: [34 - 34] -> Function `max` argument number 0 with type `DateTime` don't match expected type `Integer`"

**Expected behavior**
The aggregation functions such as min and max used on the Date fields should return the earliest and the latest dates respectively.

**GQL (please complete the following information):**
- Version 0.9.0

**Comment by AmrDeveloper** [comment]
@lmrlyv 

Aggregation functions max, min now supports Int, Float, Text, Date, Time and DateTime

https://github.com/AmrDeveloper/GQL/commit/d2b6cedca174bd242bbba616d9896ca97f7eb30b

Will be released next week on `0.11.0`

Thank you,
Amr Hesham

**Comment by AmrDeveloper** [comment]
Fixed and released on `0.11.0`
