### ISSUE TITLE
Better editing support

### ISSUE THREAD

**Issue by dclong** [AmrDeveloper/GQL#56]
**Is your feature request related to a problem? Please describe.**
After typing a long query and run it, I realize that there was a typo. The up arrow key does NOT bring back the last query (like what shell terminals would do). Copying and past the last query doesn't help much as the left/right arrow keys doesn't navigate the cursor either. Basically, I have to retype the long query and make sure not to make a typo again, which is painful.

**Describe the solution you'd like**
Better editing support. Make the up arrow key bring back the last query, and make left/right arrow keys navigate the cursor. It's even better if external editors such as Vim is supported to edit queries. 

**Describe alternatives you've considered**

**Additional context**

**Comment by AmrDeveloper** [comment]
Hello @dclong,

What you mean is Line Editor like Issue #50, i will implement a better one soon should be released on `0.10.`

Thank you,
Amr Hesham

**Comment by AmrDeveloper** [comment]
A line editor is supported now on 0.29.0, you can enable it by passing -e option

Thank you

**Comment by AmrDeveloper** [comment]
I will close it now, if there any suggestion for reporting you can create new issue related to LineEditor here or on LineEditor repo

Thank you
