### ISSUE TITLE
First time user:  Application crashes on "SELECT * from commits" on a repo with no commits yet

### ISSUE THREAD

**Issue by f0restOfHimalayas** [AmrDeveloper/GQL#58]
**Describe the bug**
Running `select * from commits` on an empty repo with no commits throws exception.

Note: Installed it for the very first time.
Installation:  `scoop install gitql`

**To Reproduce**
1. Create a folder
2. Do `git init`
3. `gitql`
4. `select * from commits`

**Expected behavior**
I am not sure what should be the expected behavior since I am using it for the first time. Generally speaking I would expect it to show 0 commits or at least don't crash!

**Screenshots**
![image](https://github.com/AmrDeveloper/GQL/assets/103200610/ecb2e95a-5697-4d5f-b68f-37a68dd597c2)

**GQL (please complete the following information):**
GitQL version 0.10.0

**Additional context**
OS: Windows
![image](https://github.com/AmrDeveloper/GQL/assets/103200610/db38170b-d751-4e87-9aa7-3c46b57304e8)

**Comment by AmrDeveloper** [comment]
Hello @f0restOfHimalayas,

Thank you for reporting, i have fixed it now and will be released on package managers next week.

Thank you,
Amr Hesham

**Comment by f0restOfHimalayas** [comment]
Thank you @AmrDeveloper
