### ISSUE TITLE
It would be nice if I could pass the query in to the command line

### ISSUE THREAD

**Issue by neilboyd** [AmrDeveloper/GQL#63]
It would be nice if I could run commands directly from the command line without having to enter the gitql shell,
eg `gitql -q 'SELECT * FROM commits'`

**Comment by AmrDeveloper** [comment]
Hello @neilboyd,

This feature is already exists in `0.10.0`, you can run this command and will be valid if the current directory contains git repository or add --repos to set repositories paths,

Thank you,
Amr Hesham

**Comment by neilboyd** [comment]
Thanks. Apparently I had an older version from winget. I'll have another look after the holidays.
