### ISSUE TITLE
Unable to install 0.10.0 and 0.11.0 from cargo

### ISSUE THREAD

**Issue by brunomenezes66** [AmrDeveloper/GQL#67]
Currently installing versions 0.10.0 and 0.11.0 using cargo install gives an error due to a dependency build:

error: failed to run custom build command for `libz-ng-sys v1.1.12`

The build seems to fail due to not having cmake installed:

failed to execute command: program not found
  is `cmake` not installed?

Installing version 0.9.0 works fine.

**Comment by AmrDeveloper** [comment]
Hello @brunomenezes66,

I think this issue is because migration to gix, so installing from cargo will requires cmake but i will double check

**Comment by AmrDeveloper** [comment]
We need to update the install documentations to mention `cmake` because it needed for gix dependencies
