### ISSUE TITLE
Columns are displayed in random order

### ISSUE THREAD

**Issue by neilboyd** [AmrDeveloper/GQL#68]
**Describe the bug**
Columns are displayed in random order.

**To Reproduce**
1. `select 1,2,3`
2. `select 1,2,3`
3. `select 1,2,3`
4. `select 1,2,3`

**Expected behavior**
The columns are displayed in the order listed in the `select` command.

**GQL (please complete the following information):**
 - Version 0.11.0

**Screenshots**

![image](https://github.com/AmrDeveloper/GQL/assets/1768373/f63ef163-7540-4123-afe2-94265db89370)

**Comment by AmrDeveloper** [comment]
Hello @neilboyd,

Thank you for reporting, i was delaying it until improve the gitql internal object structure, but i think it's time to handle it now, it will handled i next release `0.12.0`

Thank you

**Comment by AmrDeveloper** [comment]
Hello @neilboyd,

It's fixed in this commit https://github.com/AmrDeveloper/GQL/commit/c1a8c821a032ee5dc438638178b93f7d925c0f28 and will be released next week

**Comment by AmrDeveloper** [comment]
Fixed and released on `0.12.0`
