### ISSUE TITLE
Support crate package?

### ISSUE THREAD

**Issue by southorange0929** [AmrDeveloper/GQL#7]
Is it possible for us to use it with rust crate? I want to use it with own logic.

**Comment by AmrDeveloper** [comment]
Sure we should support it as a package but this step will be after make sure that we have a final design and split it into small crates for sample split the parser and the engine into two creates with full docs, and that will let you to put your logic into any pass and extend language or engine

**Comment by AmrDeveloper** [comment]
@southorange0929 now you can use any part (ast, parser, cli, engine) of the GQL as rust crates and customize with your logic

https://github.com/AmrDeveloper/GQL/tree/master/crates
