### ISSUE TITLE
Incorrect statement in function of consume_octal_number

### ISSUE THREAD

**Issue by craftslab** [AmrDeveloper/GQL#81]
**Describe the bug**

Incorrect statement in function of consume_octal_number

**To Reproduce**

```rust
// https://github.com/AmrDeveloper/GQL/blob/78ca828f952ae0ab22128eb7af0ced6c3442db93/crates/gitql-parser/src/tokenizer.rs#L811

while *pos < chars.len() && ((chars[*pos] >= '0' || chars[*pos] < '8') || chars[*pos] == '_') {
```

**Expected behavior**

```rust
while *pos < chars.len() && ((chars[*pos] >= '0' && chars[*pos] < '8') || chars[*pos] == '_') {
```

**GQL (please complete the following information):**

Version 0.14.0

**Screenshots**

None

**Comment by craftslab** [comment]
Please check it @AmrDeveloper

**Comment by AmrDeveloper** [comment]
Hello @craftslab,

Thank you for reporting with clear example and fix
