### ISSUE TITLE
Incorrect comments in function of check_all_values_are_same_type

### ISSUE THREAD

**Issue by craftslab** [AmrDeveloper/GQL#82]
**Describe the bug**

Incorrect comments in function of check_all_values_are_same_type

**To Reproduce**

```rust
// https://github.com/AmrDeveloper/GQL/blob/78ca828f952ae0ab22128eb7af0ced6c3442db93/crates/gitql-parser/src/type_checker.rs#L251

/// If they has the same type, return it or return None
```

**Expected behavior**

```rust
/// If they have the same type, return it or return None
```

**GQL (please complete the following information):**

Version 0.14.0

**Screenshots**

None

**Comment by craftslab** [comment]
Please check it @AmrDeveloper

**Comment by AmrDeveloper** [comment]
Hello @craftslab,

Thank you for reporting with clear example and fix
