### ISSUE TITLE
Remove characters of `` in the end of comments line

### ISSUE THREAD

**Issue by craftslab** [AmrDeveloper/GQL#84]
See: https://github.com/AmrDeveloper/GQL/commit/9c0dd0a73d858d4df7920fb77e9611f702c315ef#r138759473

Remove characters of `` in the end of comments line please @AmrDeveloper

_Originally posted by @craftslab in https://github.com/AmrDeveloper/GQL/issues/80#issuecomment-1950964851_

**Comment by craftslab** [comment]
Please check it @AmrDeveloper

**Comment by AmrDeveloper** [comment]
Thank you for reporting it, fixed now :D
